spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/rest_dev
    username: sheryaar
    password: sheryaar
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: rest_table_schema.sql

